<<<<<<< HEAD
name: TFSEC
=======
name:  TFSEC
>>>>>>> d6255632ff7c49550a7eecf43bc30abe14aef72d
on:
  pull_request:
  push:
    branches: [main, master]
jobs:
  terraform-tfsec:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    permissions:
      actions: write
      contents: write
      discussions: write
      pull-requests: write
      id-token: write
      security-events: write
=======
>>>>>>> d6255632ff7c49550a7eecf43bc30abe14aef72d
    steps:
    - uses: dasmeta/reusable-actions-workflows/tfsec@main
      with:
        fetch-depth: 0
    continue-on-error: true
